ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "dueDate" TIMESTAMP;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "poNumber" TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "buyerName" TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "buyerAddress" TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "buyerContact" TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS discount DECIMAL(18,2) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "taxRate" DECIMAL(6,2) NOT NULL DEFAULT 0;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "paymentBank" TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "paymentAccountNumber" TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "paymentAccountName" TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS "financeName" TEXT;

CREATE TABLE IF NOT EXISTS invoice_items (
  id SERIAL PRIMARY KEY,
  "invoiceId" INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  description TEXT NOT NULL,
  qty DECIMAL(18,2) NOT NULL DEFAULT 1,
  unit TEXT NOT NULL DEFAULT 'ls',
  "unitPrice" DECIMAL(18,2) NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_invoice_items_invoice ON invoice_items ("invoiceId");
